#+ endpoint: http://fuseki:3030/suds/query
#+ method: GET
#+ summary: Give me all sentences per aleatory and epistemic per decision

PREFIX causes: <http://uncertainty/causes#>
PREFIX framework: <http://uncertainty/framework#>
PREFIX msobd: <http://uncertainty/msobd#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX urw3: <http://uncertainty/urw3#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?natureType (COUNT(?s2) as ?sentenceCount)
WHERE {
	?_decision_iri a framework:Decision .
	?s1 msobd:hasDecision ?_decision_iri ; a framework:Sentence; owl:sameAs ?s2 .
	?s2 a urw3:Sentence; a urw3:Sentence .
    ?s2 urw3:derivationType ?nature .
    ?nature a ?natureType .
} GROUP BY ?natureType

