#+ endpoint: http://fuseki:3030/suds/update
#+ method: POST
#+ summary: register an uncertainty into SUDS (unfortunately, GRLC does not support INSERT (and CONSTRUCT does not insert data, but constructs a graph instead of a list of bindings)

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

INSERT {
?_sentence_iri rdf:type <http://uncertainty/framework#Sentence> .
}
